# Generated by Django 5.0.7 on 2025-01-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
